variable "DOC_DB_ENGINE" {}
variable "DOC_DB_ENGINE_VERSION" {}
variable "DOC_DB_INSTANCE_CLASS" {}
variable "DOC_DB_PG_FAMILY" {}
variable "PRIVATE_SUBNET_ID" {}
variable "VPC_ID" {}
variable "DOC_DB_PORT" {}
variable "PRIVATE_SUBNET_CIDR" {}
variable "PROJECT" {}
variable "ENV" {}
